name: elder_eate
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_sizer: 3.0.4+4
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  getwidget: ^2.0.3
  flutter_line_sdk: ^2.0.0
  get: ^4.3.8
  shared_preferences: ^2.0.8
  sqflite: ^2.0.0+4
  path: ^1.8.0
  image_picker: ^0.8.4+3
  flutter_typeahead: ^3.2.1
  tflite: ^1.1.2
  http: ^0.13.4
  flutter_dotenv: ^5.0.2
  path_provider: ^2.0.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - .env
      - assets/icons/
      - assets/images/
      - assets/db/elderEat.db
      - assets/model/food.tflite
      - assets/model/labels.txt
      - assets/model/fruit.tflite
      - assets/model/fruitLabels.txt
      - assets/model/TC_foods.tflite
      - assets/model/TC_labels.txt
      - assets/model/TC_foods_web.tflite
      - assets/model/TC_foods_web_labels1.txt
  fonts:
    - family: IBMPlexSansThai
      fonts:
        - asset: assets/fonts/IBMPlexSansThai-Light.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #